### PR TITLE
Multiple fixes to delayed operations, and update handling

### LINKED ISSUE #291: Exclude certain resources from autonaming
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
This is a general tracker for resources which the provider should not attempt to inject names automatically for (since the backing service is expected to name them):

Closed duplicates:
- [ ] https://github.com/pulumi/pulumi-google-native/issues/222
- [ ] https://github.com/pulumi/pulumi-google-native/issues/206
- [ ] https://github.com/pulumi/pulumi-google-native/issues/193
- [ ] https://github.com/pulumi/pulumi-google-native/issues/317

### PR DESCRIPTION
**Pull request by viveklak**
This change makes multiple fixes:
- Stores partial state more consistently in the presence of partial success (updating fix in #162). Fixes leaked resources like https://github.com/pulumi/pulumi-google-native/issues/257
- Multiple fixes for bigtable instance and cluster creation (#426)
- Add initial replace-on-changes support and provide a mechanism to selectively mark resource properties to require replacement
- Improve heuristic around identifying operations endpoints
- Make method discovery deterministic
- Test for bigtable which demonstrates encapsulates a bunch of the above.

### CODE REVIEW

File: provider/pkg/provider/diff.go [hunk 1]
```diff
@@ -44,6 +49,138 @@ func getInputsFromState(res resources.CloudAPIResource, state resource.PropertyM
 	return resource.NewPropertyMapFromMap(inputsMap)
 }
 
+// calculateDetailedDiff produced a property diff for a given object diff and a resource definition. It inspects
```
Comment (viveklak) [inline provider/pkg/provider/diff.go:52]: This is largely borrowed from azure-native. It would be ideal to leverage the replaceOnChanges support in the schema instead but a combination of https://github.com/pulumi/pulumi/issues/9158 and the fact that inputs are not a perfect subset of the properties causes this to be not ideal at the moment. The latter is likely something we need to fix anyway (codegen currently only looks at properties and not input properties) but the former would unblock broader usage of the schema's support.

File: provider/pkg/provider/provider.go [hunk 2]
```diff
@@ -544,13 +589,13 @@ func (p *googleCloudProvider) waitForResourceOpCompletion(
 			logging.V(9).Info("Getting self link URL")
 			sl, err := getKNativeSelfLinkURL(resp)
 			if err != nil {
-				return nil, err
+				return resp, err
```
Comment (viveklak) [inline provider/pkg/provider/provider.go:592]: Its important to return any partial state as part of the creation to allow checkpointing.

File: examples/bigtable-py/step1/Pulumi.yaml [hunk 3]
```diff
@@ -0,0 +1,6 @@
+name: bigtable-py-test
+runtime:
+  name: python
+  options:
+    virtualenv: venv
+description: A minimal Google Cloud Python Pulumi program
```
Comment (lblackstone) [inline examples/bigtable-py/step1/Pulumi.yaml:6]:
```suggestion
description: Test bigtable instance support
```

File: provider/pkg/gen/discovery.go [hunk 4]
```diff
@@ -24,38 +26,70 @@ import (
...
+
 // discoveryDocumentResource is a combination of REST methods that should be treated as
 // a fully capable Pulumi resource for the generation purpose.
 type discoveryDocumentResource struct {
-	createMethod, getMethod, updateMethod, deleteMethod *discovery.RestMethod
+	discoveryCRUDMethods
+	resourceName string
+}
+
+type Operation struct {
```
Comment (lblackstone) [inline provider/pkg/gen/discovery.go:40]: Docstring?

File: provider/pkg/gen/discovery.go [hunk 5]
```diff
@@ -84,11 +119,15 @@ func findResourcesImpl(docName, parentName string, rest map[string]discovery.Res
...
 				if getIamPolicy, has := res.Methods["getIamPolicy"]; has {
 					dd := discoveryDocumentResource{
-						createMethod: &restMethod,
-						getMethod:    &getIamPolicy,
-						updateMethod: &restMethod,
+						discoveryCRUDMethods: discoveryCRUDMethods{
+							createMethod: &restMethod,
+							getMethod:    &getIamPolicy,
+							updateMethod: &restMethod,
+							listMethod:   listMethod,
```
Comment (lblackstone) [inline provider/pkg/gen/discovery.go:126]: Should this be a reference? `&listMethod`

File: provider/pkg/provider/provider.go [hunk 6]
```diff
@@ -407,7 +416,44 @@ func (p *googleCloudProvider) Diff(_ context.Context, req *rpc.DiffRequest) (*rp
...
+	for k, v := range detailedDiff {
+		parts := strings.Split(k, ".")
+		changes = append(changes, parts[0])
+		v.InputDiff = true
+
+		switch v.Kind {
+		case rpc.PropertyDiff_ADD_REPLACE:
+			replaces = append(replaces, k)
+		case rpc.PropertyDiff_DELETE_REPLACE, rpc.PropertyDiff_UPDATE_REPLACE:
+			replaces = append(replaces, k)
```
Comment (lblackstone) [inline provider/pkg/provider/provider.go:433]: Looks like you could combine these into a single case statement.

File: provider/pkg/provider/provider.go [hunk 7]
```diff
@@ -407,7 +416,44 @@ func (p *googleCloudProvider) Diff(_ context.Context, req *rpc.DiffRequest) (*rp
...
+		}
+	}
+
+	deleteBeforeReplace := len(replaces) > 0
+	if v, ok := oldInputs[createBeforeDeleteFlag]; ok && v.IsBool() {
+		deleteBeforeReplace = !v.BoolValue()
```
Comment (lblackstone) [inline provider/pkg/provider/provider.go:439]: Would it make sense to name this field `__deleteBeforeReplace` to avoid having to invert the logic here? I'm not sure if `createBeforeDelete` is the exact inverse of `deleteBeforeReplace`?

File: provider/pkg/provider/provider.go [hunk 8]
```diff
@@ -407,7 +416,44 @@ func (p *googleCloudProvider) Diff(_ context.Context, req *rpc.DiffRequest) (*rp
...
+	}
+	changeType := rpc.DiffResponse_DIFF_NONE
+	if len(detailedDiff) > 0 {
+		changeType = rpc.DiffResponse_DIFF_SOME
+	}
+
+	response := rpc.DiffResponse{
+		Changes:             changeType,
+		Replaces:            replaces,
+		Stables:             []string{},
```
Comment (lblackstone) [inline provider/pkg/provider/provider.go:449]: I think you can omit this arg.

File: provider/pkg/provider/provider.go (hunk 2 above)
Comment (lblackstone) [reply provider/pkg/provider/provider.go:592]: Let's add a comment with that info to the code as well

File: provider/pkg/gen/discovery.go (hunk 5 above)
Comment (viveklak) [reply provider/pkg/gen/discovery.go:128]: listMethod is actually a pointer anyway.

File: provider/pkg/gen/discovery.go (hunk 4 above)
Comment (viveklak) [reply provider/pkg/gen/discovery.go]: Fixed.

File: provider/pkg/provider/provider.go (hunk 2 above)
Comment (viveklak) [reply provider/pkg/provider/provider.go:597]: Updated the docstring for the method

File: provider/pkg/provider/provider.go (hunk 6 above)
Comment (viveklak) [reply provider/pkg/provider/provider.go]: Done.

File: provider/pkg/provider/provider.go (hunk 7 above)
Comment (viveklak) [reply provider/pkg/provider/provider.go:442]: Thanks for pointing out - this is copied from azure-native. I changed the semantics to make this a little easier/clearer. Let me know what you think.

File: provider/pkg/provider/provider.go (hunk 8 above)
Comment (viveklak) [reply provider/pkg/provider/provider.go]: Done

File: provider/pkg/provider/provider.go (hunk 7 above)
Comment (lblackstone) [reply provider/pkg/provider/provider.go:442]: Much clearer, thanks!
