### PR TITLE
Fix operation to target URL resolution

### LINKED ISSUE #611: Invalid creationTimestamp when creating a regional network endpoint group with the beta api
### What happened?

Got the following error message:

```
google-native:compute/beta:RegionNetworkEndpointGroup (REDACTED):
    error: error sending request: googleapi: Error 400: Invalid value for field 'resource.creationTimestamp': ''. Must be a match of regex '(?:[0-9a-z][0-9a-z-]{0,48})'., invalid: "https://compute.googleapis.com/compute/beta/projects/REDACTED/regions/us-central1/networkEndpointGroups" map[name:REDACTED networkEndpointType:SERVERLESS project:REDACTED region:us-central1 serverlessDeployment:map[platform:apigateway.googleapis.com resource:projects/REDACTED/locations/us-central1/gateways/REDACTED]]
```

### Steps to reproduce

```
	// func NewNetworkEndpointGroup(ctx *Context, name string, args *NetworkEndpointGroupArgs, opts ...ResourceOption) (*NetworkEndpointGroup, error)
	neg, err := nativecomputebeta.NewRegionNetworkEndpointGroup(ctx, "REDACTEd-"+ctx.Stack(), &nativecomputebeta.RegionNetworkEndpointGroupArgs{
		Name:   pulumi.String("someidentifier-" + ctx.Stack()),
		Region: pulumi.String("us-central1),
		ServerlessDeployment: nativecomputebeta.NetworkEndpointGroupServerlessDeploymentArgs{
			Platform: pulumi.StringPtr("apigateway.googleapis.com"),
			Resource: apiGW.ID(), // Reference to an already created api gateway
		},
		NetworkEndpointType: nativecomputebeta.RegionNetworkEndpointGroupNetworkEndpointTypeServerless,
	})
	if err != nil {
		return err
	}
```

### Expected Behavior

The NEG gets created

### Actual Behavior

The error message from above.

### Versions used

```
CLI          
Version      3.36.0
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME           VERSION
gcp            6.26.0
go             unknown
google-native  0.22.0

Host     
OS       darwin
Version  12.5
Arch     x86_64

This project is written in go: executable='/Users/me/.asdf/shims/go' version='1.18.3 darwin/arm64'

Dependencies:
NAME                                        VERSION
github.com/go-openapi/spec                  v0.20.6
github.com/pulumi/pulumi-gcp/sdk/v6         v6.26.0
github.com/pulumi/pulumi-google-native/sdk  v0.22.0
github.com/pulumi/pulumi/sdk/v3             v3.37.1
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by viveklak**
We were erroneously recording the operation self-links as target identifiers for some resources. This change fixes it.

Fixes #611 

See details here: https://github.com/pulumi/pulumi-google-native/issues/611#issuecomment-1210110588

### CODE REVIEW

File: provider/pkg/provider/provider.go [hunk 1]
```diff
@@ -799,9 +799,13 @@ func (p *googleCloudProvider) waitForResourceOpCompletion(
 					return resp, err
 				}
 
+				targetLink, hasTargetLink := getTargetLink(resp)
+				if !hasTargetLink {
+					targetLink, hasTargetLink = getSelfLink(resp)
+				}
+
```
Comment (viveklak) [inline provider/pkg/provider/provider.go:806]: This is the key change - we look at both the target link and self-link properties to retrieve the target resource state.

**Review by lblackstone — APPROVED** [review]
