### PR TITLE
fix: Retry GKE cluster operations

### LINKED ISSUE #434: Retry GKE cluster operations if currently repairing
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
GKE clusters can get into an "auto-repair" state that will result in HTTP 400 responses for all operations. Currently, the provider will report the error and terminate an update rather than retrying. Instead, the provider should probably retry up to a timeout.

The error returned by the API looks something like this:
```
Error 400: Operation <operation> is currently repairing cluster <name>. Please wait and try again once it is done.
```

Note that these operations can take quite awhile to complete (> 5 mins), so the provider should output intermediate status if it is retrying an operation on a GKE cluster.

### PR DESCRIPTION
**Pull request by lblackstone**
GKE clusters have automated operations that can prevent API operations from succeeding. These API operations should be automatically retried since the cluster operation will eventually complete. This change adds a targeted retry in the provider that will be generalized in a later release.

Fix #434

### CODE REVIEW

File: provider/pkg/provider/provider.go [hunk 1]
```diff
@@ -873,7 +873,8 @@ func (p *googleCloudProvider) Delete(_ context.Context, req *rpc.DeleteRequest)
 		return &empty.Empty{}, nil
 	}
 
-	resp, err := p.client.RequestWithTimeout(res.Delete.Verb, uri, nil, 0)
+	resp, err := retryRequest(p.client, res.Delete.Verb, uri, nil)
```
Comment (viveklak) [inline provider/pkg/provider/provider.go:876]: 👍🏾  - I guess we need to add this to other crud methods as well?

**Review by viveklak — COMMENTED** [review]
Looks good. Looks like the tests are failing because of resource availability in zones though. Hopefully rerunning works. If not, we might have to switch the region for tests in github action workflows.

File: provider/pkg/provider/provider.go (hunk 1 above)
Comment (lblackstone) [reply provider/pkg/provider/provider.go:876]: Yep, exactly. I'm testing locally with Delete at the moment, and then I'll roll it out to the other operations when I've verified it's working as expected.

Comment (viveklak) [reply provider/pkg/provider/provider.go:876]: Thanks for pursuing this approach. Would also be good to update the GKE test with something that adds a nodepool or something in second step which should trigger the repairing state as an integration test for this.

Comment (lblackstone) [reply provider/pkg/provider/provider.go:876]: > Would also be good to update the GKE test with something that adds a nodepool or something in second step which should trigger the repairing state as an integration test for this.

We chatted offline about this and decided to defer this until after the planned refactoring. I tested this workflow locally, and it takes ~30 minutes to run, so we need to be mindful of how to include this in CI.

**Review by viveklak — APPROVED** [review]
